### ISSUE TITLE
 Baremetal-#ENHANCE00002 Problem for Distributed vMX

### ISSUE THREAD

**Issue by achyarnurandi** [achyarnurandi/virtuallab-baremetal#5]
## Baremetal-#ENHANCE00002 Problem after deployed that using 20.xR version

- [x] Need to fix the back-end code of vMX for distributed
- [x] Re-test the vMX can running with those items
- [x] Starting to create certain interface and do the test related to protocol

**Comment by netcodebynull** [comment]
Okay.. let me check what I can do with this stuff. Inviting just to give me this shit assignment. How shame

**Comment by netcodebynull** [comment]
Oh yeah. I forgot. I locked this as ISSUE0004

**Comment by netcodebynull** [comment]
Need additional time to fix it due to crash with vFP image. Will inform soon

**Comment by netcodebynull** [comment]
Noted. It's not rushing at all. But please consider it due to important request from testing engineer

**Comment by achyarnurandi** [comment]
Noted. It's not rushing at all. But please consider it due to important request from testing engineer @netcodebynull
